TOOLS = [{'type': 'function',
  'function': {'name': 'analyze_ecommerce_sample',
               'description': '200 satırlık sample e-ticaret datası üzerinden stok, kategori, SKU, satış, revenue, '
                              'fiyat, C2D, B2D, funnel, PDP, A2C, checkout, OOS, overstock ve stock coverage '
                              'sorularını cevaplar. Stok, satış, funnel, kategori, marka, SKU, revenue, C2D, B2D gibi '
                              'geniş analiz sorularında varsayılan olarak bunu kullan.',
               'parameters': {'type': 'object',
                              'properties': {'question': {'type': 'string',
                                                          'description': 'Kullanıcının doğal dilde sorduğu e-ticaret '
                                                                         'analiz sorusu'}},
                              'required': ['question']}}},
 {'type': 'function',
  'function': {'name': 'execute_recommended_action',
               'description': 'Önerilen aksiyonları çalıştırır. Replenishment planı, stok riski olan SKU listesi, '
                              "kampanya/görünürlük planı, riskli segment detaylandırma ve Excel'e indirilecek aksiyon "
                              'çıktıları üretir.',
               'parameters': {'type': 'object',
                              'properties': {'question': {'type': 'string',
                                                          'description': 'Kullanıcının aksiyon isteği. Örn: C2D/B2D '
                                                                         "güçlü ama stok riski olan SKU'lar için "
                                                                         'replenishment planı yap.'}},
                              'required': ['question']}}},
 {'type': 'function',
  'function': {'name': 'generate_price_competition_from_uploaded_inputs',
               'description': "Şirketin GTIN'li ürün/funnel input datasını Merchant Center benchmark datasıyla GTIN "
                              "üzerinden join ederek fiyat rekabeti insight'ı üretir. Internal benchmark kullanmaz.",
               'parameters': {'type': 'object',
                              'properties': {'category': {'type': 'string',
                                                          'description': 'Analiz edilecek kategori, marka veya ürün '
                                                                         'grubu. Örn: Mobile, Tablet, Fashion, genel'},
                                             'period_name': {'type': 'string',
                                                             'description': 'Analiz dönemi adı. Örn: Tatil dönemi, Son '
                                                                            '7 gün, selected_period'}},
                              'required': ['category']}}},
 {'type': 'function',
  'function': {'name': 'calculate_business_metric',
               'description': 'Şirket Excel datası üzerinde ortalama, toplam, adet, minimum, maksimum, medyan, '
                              'top/bottom, marka/kategori kırılımı gibi matematiksel business hesaplamaları yapar. '
                              "APPLE ürünlerinin ortalama fiyatı, GSM kategorisinin toplam revenue'u, B2D ortalaması, "
                              'marka bazında PDP gibi sorularda kullanılır.',
               'parameters': {'type': 'object',
                              'properties': {'question': {'type': 'string',
                                                          'description': 'Kullanıcının doğal dilde sorduğu '
                                                                         'matematiksel business sorusu'}},
                              'required': ['question']}}},
 {'type': 'function',
  'function': {'name': 'generate_category_insight',
               'description': 'Kategori, sektör, dönem, fırsat/risk, kazanan-kaybeden segment, stok/fiyat/talep/funnel '
                              'nedeni ve CEO özeti sorularında kategori insight analizi üretir.',
               'parameters': {'type': 'object',
                              'properties': {'category': {'type': 'string',
                                                          'description': 'Analiz edilecek kategori. Örn: Cep '
                                                                         'Telefonları, GSM, Tabletler, Kulaklıklar, '
                                                                         'Giyilebilir Teknoloji. Belirsizse genel.'},
                                             'sector': {'type': 'string',
                                                        'description': 'Sektör tipi. consumer_electronics, fashion, '
                                                                       'fmcg veya marketplace_general.',
                                                        'enum': ['consumer_electronics',
                                                                 'fashion',
                                                                 'fmcg',
                                                                 'marketplace_general']},
                                             'period_name': {'type': 'string',
                                                             'description': 'Analiz dönemi. Örn: selected_period, '
                                                                            'tatil dönemi, son 7 gün.'},
                                             'question': {'type': 'string',
                                                          'description': 'Kullanıcının doğal dilde sorduğu tam '
                                                                         'kategori insight sorusu.'}},
                              'required': ['category', 'question']}}},
 {'type': 'function',
  'function': {'name': 'get_stock_level',
               'description': 'Belirli bir ürünün stok miktarını döner',
               'parameters': {'type': 'object',
                              'properties': {'product_id': {'type': 'string',
                                                            'description': 'Ürün kodu, örn: SKU-001'}},
                              'required': ['product_id']}}},
 {'type': 'function',
  'function': {'name': 'get_all_stock',
               'description': 'Tüm ürünlerin stok listesini getirir. Karşılaştırma, en fazla/az, toplam stok gibi '
                              'sorularda kullan.',
               'parameters': {'type': 'object', 'properties': {}}}},
 {'type': 'function',
  'function': {'name': 'get_daily_sales_report',
               'description': 'Günlük satış raporunu getirir',
               'parameters': {'type': 'object', 'properties': {}}}},
 {'type': 'function',
  'function': {'name': 'check_low_stock',
               'description': 'Stoku az olan ürünleri listeler. Eşik belirtilmezse varsayılan 10 kabul edilir.',
               'parameters': {'type': 'object',
                              'properties': {'threshold': {'type': 'integer',
                                                           'description': 'Minimum stok eşiği, örn: 10'}},
                              'required': []}}},
 {'type': 'function',
  'function': {'name': 'get_out_of_stock',
               'description': 'Stoku tamamen tükenmiş ürünleri listeler',
               'parameters': {'type': 'object', 'properties': {}}}},
 {'type': 'function',
  'function': {'name': 'search_product_by_name',
               'description': 'Ürün adıyla arama yapar. SKU kodu bilinmiyorsa kullan.',
               'parameters': {'type': 'object',
                              'properties': {'name': {'type': 'string', 'description': 'Aranacak ürün adı, örn: Elma'}},
                              'required': ['name']}}},
 {'type': 'function',
  'function': {'name': 'get_stock_value',
               'description': 'Tüm ürünlerin toplam stok değerini hesaplar (adet x fiyat)',
               'parameters': {'type': 'object', 'properties': {}}}},
 {'type': 'function',
  'function': {'name': 'update_stock',
               'description': 'Belirli bir ürünün stok miktarını günceller',
               'parameters': {'type': 'object',
                              'properties': {'product_id': {'type': 'string', 'description': 'Ürün kodu, örn: SKU-001'},
                                             'quantity': {'type': 'integer', 'description': 'Yeni stok miktarı'}},
                              'required': ['product_id', 'quantity']}}},
 {'type': 'function',
  'function': {'name': 'get_order_status',
               'description': 'Belirli bir siparişin durumunu getirir',
               'parameters': {'type': 'object',
                              'properties': {'order_id': {'type': 'string',
                                                          'description': 'Sipariş numarası, örn: ORD-001'}},
                              'required': ['order_id']}}},
 {'type': 'function',
  'function': {'name': 'get_all_orders',
               'description': 'Tüm siparişleri listeler',
               'parameters': {'type': 'object', 'properties': {}}}},
 {'type': 'function',
  'function': {'name': 'get_pending_orders',
               'description': 'Bekleyen siparişleri listeler',
               'parameters': {'type': 'object', 'properties': {}}}},
 {'type': 'function',
  'function': {'name': 'get_orders_by_customer',
               'description': 'Belirli bir müşterinin siparişlerini getirir',
               'parameters': {'type': 'object',
                              'properties': {'customer': {'type': 'string', 'description': 'Müşteri adı, örn: Ali'}},
                              'required': ['customer']}}},
 {'type': 'function',
  'function': {'name': 'update_order_status',
               'description': 'Sipariş durumunu günceller',
               'parameters': {'type': 'object',
                              'properties': {'order_id': {'type': 'string',
                                                          'description': 'Sipariş numarası, örn: ORD-001'},
                                             'status': {'type': 'string',
                                                        'description': 'Yeni durum: Beklemede, Kargoda, Teslim Edildi, '
                                                                       'İptal'}},
                              'required': ['order_id', 'status']}}},
 {'type': 'function',
  'function': {'name': 'get_todays_orders',
               'description': 'Bugünkü siparişleri listeler',
               'parameters': {'type': 'object', 'properties': {}}}},
 {'type': 'function',
  'function': {'name': 'get_total_revenue',
               'description': 'Toplam geliri hesaplar (teslim edilen siparişler)',
               'parameters': {'type': 'object', 'properties': {}}}},
 {'type': 'function',
  'function': {'name': 'get_best_selling_product',
               'description': 'En çok satan ürünü getirir',
               'parameters': {'type': 'object', 'properties': {}}}},
 {'type': 'function',
  'function': {'name': 'get_sales_summary',
               'description': 'Genel satış özetini getirir. Toplam sipariş, teslim, iptal ve gelir bilgisi.',
               'parameters': {'type': 'object', 'properties': {}}}},
 {'type': 'function',
  'function': {'name': 'get_low_stock_report',
               'description': 'Kritik stok seviyesindeki ürünlerin raporunu getirir',
               'parameters': {'type': 'object', 'properties': {}}}},
 {'type': 'function',
  'function': {'name': 'get_stock_turnover',
               'description': 'Ürün bazında satış ve mevcut stok karşılaştırması yapar',
               'parameters': {'type': 'object', 'properties': {}}}},
 {'type': 'function',
  'function': {'name': 'analyze_cross_performance',
               'description': 'E-ticaret metriklerini (PDP, A2C, Trans, C2D, B2D), Google Trends mevsimsel talep verilerini, Google Merchant Center fiyat rekabeti benchmarklarını ve PPC reklam bid yönlendirmelerini çaprazlayarak stratejik analiz yapar.',
               'parameters': {'type': 'object',
                              'properties': {'question': {'type': 'string',
                                                          'description': 'Kullanıcının doğal dilde sorduğu fiyat rekabeti, mevsimsel talep veya PPC optimizasyonu sorusu.'}},
                              'required': ['question']}}},
  {'type': 'function',
   'function': {'name': 'analyze_gfk_market_share',
                'description': 'GfK Leaderpanel verilerinden kategori bazında pazar büyüklüğü (TRY), MediaMarkt pazar payı (Ihs %), haftalık büyüme (WoW%) ve rank bilgisi üretir. '
                               '"Pazar payımız nedir?", "En çok büyüyen kategori hangisi?", "Bu hafta vs geçen hafta satış değişimi nasıl?", '
                               '"AIR CONDITIONERS pazarı büyüdü mü?", "MediaMarkt kaçıncı sırada?" sorularında kullan.',
                'parameters': {'type': 'object',
                               'properties': {'question': {'type': 'string',
                                                           'description': 'Pazar payı, kategori büyümesi veya haftalık karşılaştırma sorusu.'}},
                               'required': ['question']}}},
  {'type': 'function',
   'function': {'name': 'analyze_gfk_brand_performance',
                'description': 'GfK Leaderpanel Brand sheet\'inden marka bazında haftalık MediaMarkt internet satış payı (%) ve WoW değişimini analiz eder. '
                               '"SAMSUNG pazar payı nedir?", "APPLE vs SAMSUNG karşılaştır", "Smartphones\'da hangi marka önde?", '
                               '"MediaMarkt\'ta en güçlü marka hangisi?", "BOSCH bu hafta kaçıncı sırada?" sorularında kullan.',
                'parameters': {'type': 'object',
                               'properties': {'question': {'type': 'string',
                                                           'description': 'Marka bazında pazar payı veya haftalık karşılaştırma sorusu.'}},
                               'required': ['question']}}},
  {'type': 'function',
   'function': {'name': 'analyze_gfk_sku_ranking',
                'description': 'GfK SKU Leaderpanel verisinden ürün grubu ve marka bazında satış sıralaması (rank 1, 2, 3...) ve model listesi üretir. '
                               '"Washing Machines\'de top 10 SKU", "SAMSUNG\'un en çok satan modelleri", "LG bulaşık makinesinde hangi model 1. sırada?", '
                               '"GfK\'ya göre 1. sıradaki ürünler", "Smartphone\'larda APPLE\'ın modelleri hangileri?" sorularında kullan.',
                'parameters': {'type': 'object',
                               'properties': {'question': {'type': 'string',
                                                           'description': 'Ürün sıralaması veya model listesi sorusu.'}},
                               'required': ['question']}}},
  {'type': 'function',
   'function': {'name': 'analyze_gfk_combined',
                'description': 'GfK pazar verilerini (pazar büyüklüğü, MediaMarkt payı, WoW büyüme) ile şirketin ecommerce metriklerini (C2D, B2D, revenue, stok) birleştirerek cross analiz üretir. '
                               '"GfK market share\'imizi C2D ile kıyasla", "Pazar büyürken satışımız neden düşüyor?", "SAMSUNG\'un GfK vs ecommerce performansı", '
                               '"Pazar genişliyor ama biz yararlanamıyor muyuz?", "GfK ile iç satışlarımızı karşılaştır" sorularında kullan.',
                'parameters': {'type': 'object',
                               'properties': {'question': {'type': 'string',
                                                           'description': 'GfK ve ecommerce verilerini birleştiren cross analiz sorusu.'}},
                               'required': ['question']}}}]
